refactor improve performance:
ronenhamias/scalecube-services pull request #110
Opened 2018-05-26 03:24 UTC by ronenhamias

* reduce the preasure on class for name on each request by caching the return type when building a proxy.
* do not call ServiceLoader on each request.
* improve tests not create gateway on each test.

Test included:
```java
package io.scalecube.services.benchmarks;

import io.scalecube.services.Microservices;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;

import reactor.core.publisher.Flux;

public class ServicesBenchmark {

  public static AtomicInteger total = new AtomicInteger(0);

  public static void main(String[] args) throws InterruptedException, ExecutionException {
    Microservices gateway = Microservices.builder().build().startAwait();

    Microservices node = Microservices.builder()
        .seeds(gateway.cluster().address())
        .services(new BenchmarkServiceImpl())
        .build()
        .startAwait();

    Flux.from(gateway.call().create().api(BenchmarkService.class)
        .requestMany(new BenchmarkMessage("hello joe", 1_000_000)))
        .blockLast();
    Thread.sleep(1000);

    ExecutorService exec = Executors.newFixedThreadPool(6);
    long both = System.currentTimeMillis();
    CompletableFuture.allOf(
        runClient(gateway, 1_000_000, exec),
        runClient(gateway, 1_000_000, exec),
        runClient(gateway, 1_000_000, exec),
        runClient(gateway, 1_000_000, exec),
        runClient(gateway, 1_000_000, exec),
        runClient(gateway, 1_000_000, exec))
        .get();
    long done = System.currentTimeMillis();
    System.out.println("requested : " + total + " :  at rate of(ms): " + (total.get() / (done - both)));
    exec.shutdownNow();
  }

  static AtomicInteger executerNumber = new AtomicInteger();

  static CompletableFuture<Void> runClient(Microservices gateway, int count, ExecutorService exec) {
    BenchmarkMessage request = new BenchmarkMessage("hello joe", count);
    total.addAndGet(count);
    return CompletableFuture.runAsync(() -> {
      int myExecutionNumber = executerNumber.incrementAndGet();
      System.out.println("### Task no." + myExecutionNumber + " request for(" + count + ")");
      long start = System.currentTimeMillis();
      Flux.from(gateway.call().create().api(BenchmarkService.class)
          .requestMany(request))
          .blockLast();
      long end = System.currentTimeMillis();
      System.out.println("request many " + myExecutionNumber + ": " + (end - start));
    }, exec);
  }
}
```

2018-05-27 19:07 UTC, ronenhamias commented
After this fix i reach 90,000 stream events per sec (locally)

2018-05-28 09:21 UTC, segabriel commented
I  ran benchmarks (https://github.com/scalecube/scalecube-services/pull/109) on my home laptop
results (for test requestOne, nThreads=4, duretion=5min) were following:

    count=834933, 
    min=1.15303, 
	max=801.103885, 
	mean=88.53025134779888, 
	stddev=49.85243414974958, 
	median=84.465437, 
	p75=121.347366, 
	p95=172.00612999999998, 
	p98=195.691731, 
	p99=213.447085, 
	p999=342.67309, 
	mean_rate=2783.1789277083512, 
	m1=2925.5056291887413, 
	m5=1952.4524752561217, 
	m15=1119.674823708388, 
	rate_unit=events/second, duration_unit=milliseconds

and after applying these improvements:

	count=3721783, 
	min=0.124098, 
	max=129.73688099999998, 
	mean=19.549434026790586, 
	stddev=16.914100802323368, 
	median=16.497311, 
	p75=33.275011, 
	p95=49.409980999999995, 
	p98=57.662079, 
	p99=64.08773, 
	p999=77.05458399999999, 
	mean_rate=12406.269157319271, 
	m1=12913.238396023744, 
	m5=8970.266334641301, 
	m15=5549.400468304719, 
	rate_unit=events/second, duration_unit=milliseconds

so it's very nice improvements!

2018-05-28 12:56 UTC, aharonha commented on services/src/main/java/io/scalecube/services/ServiceCall.java
> +          .data(method.getParameterCount() != 0 ? params[0] : NullData.NULL_DATA)
Is it just me or `!=0` may imply more than 1 parameter

2018-05-28 14:27 UTC, aharonha commented on services-codec/src/main/java/io/scalecube/services/codec/ServiceMessageDataCodec.java
>  public final class ServiceMessageDataCodec {
What is the difference between `ServiceMessageDataCodec` and `ServiceMessageCodec`?

2018-05-28 16:28 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/ServiceCall.java
> +          .data(method.getParameterCount() != 0 ? params[0] : NullData.NULL_DATA)
yes no more then one paramter

2018-05-28 16:29 UTC, ronenhamias commented on services-codec/src/main/java/io/scalecube/services/codec/ServiceMessageDataCodec.java
>  public final class ServiceMessageDataCodec {
service message decode headers and not body
and service data codec decode only data

2018-05-29 08:07 UTC, artem-v requested changes

2018-05-29 08:07 UTC, artem-v commented on services-codec/src/main/java/io/scalecube/services/codec/ServiceMessageCodec.java
> -        DataCodec dataCodec = DataCodec.getInstance(contentType);
Those two lines were  correct. What was not is implementation of the `DataCodec.getInstance()`. It has to cache once loaded codec classes and on subsequent calls return from hash map.

2018-05-29 08:07 UTC, artem-v commented on services-codec/src/main/java/io/scalecube/services/codec/ServiceMessageDataCodec.java
> -        DataCodec dataCodec = DataCodec.getInstance(contentType);
Those two lines were  correct. What was not is implementation of the `DataCodec.getInstance()`. It has to cache once loaded codec classes and on subsequent calls return from hash map.

2018-05-29 08:07 UTC, artem-v commented on services-codec/src/main/java/io/scalecube/services/codec/ServiceMessageDataCodec.java
> -      DataCodec dataCodec = DataCodec.getInstance(contentType);
Those two lines were  correct. What was not is implementation of the `DataCodec.getInstance()`. It has to cache once loaded codec classes and on subsequent calls return from hash map.

2018-05-29 09:36 UTC, artem-v approved these changes

2018-05-29 10:01 UTC, merged