Refactor code for routers
ronenhamias/scalecube-services pull request #135
Opened 2018-06-13 16:07 UTC by dmytro-lazebnyi

2018-06-13 17:24 UTC, artem-v commented
o_O

2018-06-13 21:15 UTC, dmytro-lazebnyi commented
@artem-v 
Just some improvements from my point of view.
Obviously, PR should not be merged, if no one sees need in this changes :)

2018-06-14 05:17 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/Reflect.java
> +          LOGGER.warn("Unable to find instance of {} router, used RoundRobinServiceRouter instead", injection.router());
this is good idea?
it might come as a surprise for a user that didnt read this warning

2018-06-14 06:07 UTC, dmytro-lazebnyi commented on services/src/main/java/io/scalecube/services/Reflect.java
> +          LOGGER.warn("Unable to find instance of {} router, used RoundRobinServiceRouter instead", injection.router());
I left this part of behavior almost as is - you can see that the main difference is that I changed logic of using `Optional`.
`Router router = Optional.ofNullable(Routers.getRouter(routerClass)).orElseGet(...)`
instead of
`Router router = Optional.of(routerClass).map(Routers::getRouter).orElseGet(...)`

I also agree that it is not obviously for user what kind of `Router` is used by default. So I'm trying to find better solution.

2018-06-15 15:25 UTC, dmytro-lazebnyi commented
Added description of PR https://github.com/scalecube/scalecube-services/pull/135#issue-194639259

2018-06-15 18:35 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/Reflect.java
> +          LOGGER.warn("Unable to find instance of {} router, used RoundRobinServiceRouter instead", injection.router());
so i guess if we do improvement maybe lets consider?

2018-06-19 10:54 UTC, artem-v requested changes

2018-06-19 10:54 UTC, artem-v commented on services/src/main/java/io/scalecube/services/Reflect.java
> +        if (!routerClass.isInterface()) {
Router class cant be null?

2018-06-19 10:54 UTC, artem-v commented on services-api/src/main/java/io/scalecube/services/annotations/Inject.java
> +  Class<? extends Router> router() default Router.class;
I liked null rouetr actually

2018-06-19 10:54 UTC, artem-v commented on services/src/main/java/io/scalecube/services/routing/Routers.java
> +import com.google.common.base.Throwables;
Maybe lets go with out guava?
Just copy their code of wrapping exception into some utility class

2018-06-19 11:00 UTC, dmytro-lazebnyi commented on services/src/main/java/io/scalecube/services/Reflect.java
> +        if (!routerClass.isInterface()) {
No, because routerClass is returned from `router()` method from `@Inject` annotation.
And this method is declared as
`Class<? extends Router> router() default Router.class;`

2018-06-19 11:03 UTC, dmytro-lazebnyi commented on services-api/src/main/java/io/scalecube/services/annotations/Inject.java
> +  Class<? extends Router> router() default Router.class;
I think it is redundant because it was not used anywhere as it. It just was annotated with newly added `@Null` annotation (which is also reduntant from my point of view) and this annotation is checked in `Reflect` class during injection for setting `RoundRobinServiceRouter` instead of `NullRouter`.
`if (routerClass.isAnnotationPresent(Null.class)) {
          routerClass = RoundRobinServiceRouter.class;
        }
`

2018-06-19 13:05 UTC, dmytro-lazebnyi commented on services/src/main/java/io/scalecube/services/routing/Routers.java
> +import com.google.common.base.Throwables;
Guava has been already used before in `Service Discovery` for the same purposes - to propagate exception. I just used it once more :)

2018-06-19 14:52 UTC, artem-v commented
Let's make changes that we agreed and then +1 to merge,

2018-06-19 15:21 UTC, dmytro-lazebnyi commented
Removed `router` from `Microservices` as it was discussed with @artem-v.
Updated PR description.

2018-06-19 15:27 UTC, dmytro-lazebnyi commented
According to discussion with @artem-v:
* Removed `router` from `Microservices`
* Removed unnecessary method `routes` from `Router` interface.

2018-06-20 04:19 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/routing/Routers.java
> +import com.google.common.base.Throwables;
+1 not using Guava this dependency comes from cluster and we work to remove it.

2018-06-20 04:20 UTC, ronenhamias commented on services-api/src/main/java/io/scalecube/services/annotations/Inject.java
> +  Class<? extends Router> router() default Router.class;
+1 for not using NullRouter

2018-06-20 04:22 UTC, ronenhamias commented
+1 for changes

2018-06-20 08:00 UTC, snripa approved these changes

2018-06-20 11:12 UTC, artem-v approved these changes

2018-06-20 11:12 UTC, merged