add support for REQUEST_CHANNEL
ronenhamias/scalecube-services pull request #140
Opened 2018-06-17 15:20 UTC by ronenhamias

request bidi and test success case ServiceCall

```java
  @ServiceMethod
  Flux<GreetingResponse> bidiGreeting(Flux<GreetingRequest> request);
```

2018-06-19 14:55 UTC, artem-v commented
```java
  @ServiceMethod
  Flux<GreetingResponse> bidiGreeting(Publlisher<GreetingRequest> request);
```
Would n't be nice to have `Publsiher` at interface. I dont know why, but rSocket follows this convention. And we are as well in several places at the codebase.

2018-06-19 15:11 UTC, artem-v requested changes
Cosmetic changes are needed.

2018-06-19 15:11 UTC, artem-v commented on services/src/main/java/io/scalecube/services/ServiceCall.java
> +          } else if (methodInfo.communicationMode().equals(REQUEST_CHANNEL)) {
Why `else if` block instead of just another `case` occurence after `case REQUEST_STREAM`  occurence.

2018-06-19 15:11 UTC, artem-v commented on services/src/main/java/io/scalecube/services/ServiceCall.java
> +                        mono -> methodInfo.isRequestTypeServiceMessage() ? mono : mono.map(ServiceMessage::data));
This `methodInfo.isRequestTypeServiceMessage`  can be assigned to some avriable to save some space at lines. Same applies to `methodInfo.parameterizedReturnType()`; it can be define once upper.

2018-06-19 15:11 UTC, artem-v commented on services/src/main/java/io/scalecube/services/ServiceCall.java
> +            ServiceMessage request = ServiceMessage.builder()
Looks like code block at https://github.com/scalecube/scalecube-services/pull/140/files#diff-c402059b5663b50c40754f48b7677f9cR277 is similar to this one. 
Looks like we need private method `ServiceMessage toMessage(MethodInfo mi, Object data)`

2018-06-19 15:11 UTC, artem-v commented on services/src/test/java/io/scalecube/services/RemoteServiceTest.java
> +
Plz remove those empty lines

2018-06-19 15:25 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/ServiceCall.java
> +          } else if (methodInfo.communicationMode().equals(REQUEST_CHANNEL)) {
becouse of the request handeling is totally diffrent when you request stream

2018-06-20 09:24 UTC, artem-v approved these changes

2018-06-20 09:25 UTC, merged