[WIP] Netty EventLoopGroup to be customizable for Microservices instance
ronenhamias/scalecube-services pull request #155
Opened 2018-06-26 11:26 UTC by snripa

2018-06-26 11:57 UTC, dmytro-lazebnyi commented on services-transport/src/main/java/io/scalecube/services/transport/ServiceTransportConfig.java
> +  private final ExecutorService serverEventLoopGroup;
Why don't use interface `EventLoopGroup`?
It also helps to avoid casting to `EventLoopGroup` in `RSocketServiceTransport.configure`.

In other case if you really need declare it as `ExecutorService` you should rename variable from `clientEventLoopGroup` to `clientExecutorService` (and the same for `server*` variable).

2018-06-26 13:00 UTC, artem-v requested changes
So far cosmetic changes are required

2018-06-26 13:00 UTC, artem-v commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/client/RSocketClientTransport.java
> +  private final Optional<EventLoopGroup> customEventLoopGroup;
Let's not have optional field

2018-06-26 13:00 UTC, artem-v commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/client/RSocketClientTransport.java
> +    this(codec, Optional.empty());
Here we can path just null

2018-06-26 13:00 UTC, artem-v commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/RSocketServiceTransport.java
Plz remove two lines below : )

2018-06-26 13:00 UTC, artem-v commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/server/RSocketServerTransport.java
> +          customEventLoopGroup.ifPresent(options::eventLoopGroup);
See previous comments above regarding `optional` approach

2018-06-26 15:16 UTC, ronenhamias commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/server/RSocketServerTransport.java
> +          customEventLoopGroup.ifPresent(options::eventLoopGroup);
please check this is no impact on performance as result of this change
i just run the benchmarks and the result is 50% from prev benchmarks.

2018-06-26 15:19 UTC, ronenhamias requested changes
please include benchmarks results before and after this change to prove this change is needed.

2018-06-26 19:36 UTC, ronenhamias commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/server/RSocketServerTransport.java
> +          customEventLoopGroup.ifPresent(options::eventLoopGroup);
this change for some reason causes the CPU to spike.
![image](https://user-images.githubusercontent.com/1706296/41935121-54a9b6d8-7991-11e8-8919-c40f93afc828.png)

2018-06-27 06:41 UTC, snripa commented on services-transport/src/main/java/io/scalecube/services/transport/ServiceTransportConfig.java
> +  private final ExecutorService serverEventLoopGroup;
I was asked not to add dependency on Netty...
will rename fields, sure

2018-06-27 06:58 UTC, snripa commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/server/RSocketServerTransport.java
> +          customEventLoopGroup.ifPresent(options::eventLoopGroup);
@ronenhamias what benchmarks do you suggest me to run?

2018-06-29 13:19 UTC, artem-v commented
Let's not merge this PR so far. It's very important for perf. I have some ideas at this PR. Let's keep it for now.

2018-08-10 16:16 UTC, artem-v commented
Closing it in favour of https://github.com/scalecube/scalecube-services/pull/244

2018-08-10 16:16 UTC, closed without merging