Decouple scalecube-cluster by applying discovery module
ronenhamias/scalecube-services pull request #223
Opened 2018-07-30 06:29 UTC by ronenhamias

this pull request focus only on decouple service discovery from cluster by providing a model of discovery providers such as scalecube-cluster

**Motivations:**
1. Allow users to implement Discovery provider
2. Provider a clear model for discovery behavior in scalecube services (mesh)
3. Regulate the interaction model with discovery module.

**The solution:**
1. provide discovery api as part of service-api
2. move discovery to separated module and load using ServiceLoader. 
3. implement scalecube-cluster as discovery provider.. 

#161

2018-07-30 12:17 UTC, artem-v requested changes
Cluster is cluster, discovery is a discovery, service registry is a service registry. Why we putting `service registry` under package `discovery`

2018-07-30 12:17 UTC, artem-v commented on pom.xml
> +    <module>services-discovery</module>
Just `discovery` to follow already established convention.

2018-07-30 12:17 UTC, artem-v commented on services-api/pom.xml
>  <?xml version="1.0"?>
Plz setup following settings for indentation for xml: 2(tab), 2(indent), 4(continuation indent)

2018-07-30 12:29 UTC, artem-v requested changes

2018-07-30 12:29 UTC, artem-v commented on services-api/src/main/java/io/scalecube/services/discovery/api/ServiceDiscovery.java
> +  Flux<ServiceMessage> listenGossip();
Gossip is not relevant to _discovery_.

2018-07-30 12:29 UTC, artem-v commented on services-api/src/main/java/io/scalecube/services/discovery/api/ServiceDiscovery.java
> +  Mono<String> spreadGossip(ServiceMessage gossip);
Gossip is not relevant to _discovery_.

2018-07-30 12:58 UTC, artem-v requested changes

2018-07-30 12:58 UTC, artem-v commented on services-discovery/src/main/java/io/scalecube/services/discovery/ScalecubeServiceDiscovery.java
> +  public Mono<String> spreadGossip(ServiceMessage gossip) {
Why _gossip_ is part of to discovery api ?

2018-07-30 12:58 UTC, artem-v commented on services/src/main/java/io/scalecube/services/Microservices.java
What is `aliasName` ?

2018-07-30 12:58 UTC, artem-v commented on services/src/main/java/io/scalecube/services/Microservices.java
> +  public String aliasName() {
What is `aliasName` ?

2018-07-30 13:18 UTC, artem-v requested changes

2018-07-30 13:18 UTC, artem-v commented on services-discovery/src/main/java/io/scalecube/services/discovery/ScalecubeServiceDiscovery.java
> +  public Flux<ServiceMessage> listenGossip() {
Gossip is not relevant to disocvery

2018-07-30 13:18 UTC, artem-v commented on services-api/src/main/java/io/scalecube/services/discovery/api/ServiceDiscovery.java
> +  public static final String SERVICE_METADATA = "service";
This constant is not part of public api, it's part of implementation specifics, better put it at other place

2018-07-30 13:18 UTC, artem-v commented on services-discovery/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
For xml : ident 2, tab 2, continuation indent 4

2018-07-30 13:18 UTC, artem-v commented on services-discovery/pom.xml
> +
Remove following two `scalecube-services-jackson`   entries and depend on jackson directly, ` scalecube-services-jackson` is not supposed to maintain  cluster metadata.

2018-07-30 13:18 UTC, artem-v commented on services-discovery/src/main/resources/META-INF/services/io.scalecube.services.discovery.api.ServiceDiscovery
> +io.scalecube.services.discovery.ScalecubeServiceDiscovery
Don't u think that putting implementation under package without `api`  and keeping interface at package with `.api` is somewhat  confusing.

2018-07-30 13:18 UTC, artem-v commented on services/pom.xml
In this `services` module we should not have dependencies neither on  `scalecube-cluster` nor on `scalecube-services-discovery`. Otherwise, if we hardcode dependency on discovery here, then end client  wouldn't be able to provide his own discovery mechanism.

2018-07-30 13:18 UTC, artem-v commented on services/src/main/java/io/scalecube/services/Microservices.java
> +  private String aliasName;
What's `aliasName` ?

2018-07-30 17:59 UTC, ronenhamias commented on pom.xml
> +    <module>services-discovery</module>
other modules called
```
 <module>services-api</module>
    <module>services-transport</module>
    <module>services-codec</module>
    <module>services-codec-jackson</module>
```

i guess this prefix make the discovery specific to services.

2018-07-30 18:01 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/Microservices.java
> +  public String aliasName() {
alias name is a user defined name to this endpoint somewhat like the names dockers get when they start

it can be good for tracing when you have a node that host service a and service b

and you want to say this deployment unit for me called "something meaningful"

2018-07-30 18:05 UTC, ronenhamias commented on services-discovery/src/main/resources/META-INF/services/io.scalecube.services.discovery.api.ServiceDiscovery
> +io.scalecube.services.discovery.ScalecubeServiceDiscovery
hmm... interface is an api no?

2018-07-30 18:14 UTC, ronenhamias commented on services-discovery/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
lets agree on indent 4 spaces for xml this configuration is not something i see possible

2018-07-30 18:32 UTC, ronenhamias commented on services-api/pom.xml
>  <?xml version="1.0"?>
lets agree on indent 4 spaces for xml this configuration is not something i see possible

2018-07-30 19:00 UTC, ronenhamias commented on services/pom.xml
moved to testing scope

2018-07-30 19:00 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/Microservices.java
removed for this pull request

2018-07-31 20:22 UTC, artem-v commented on services-api/pom.xml
>  <?xml version="1.0"?>
I talked to @aharonha about this indent issue in eclipse and looks like he found a solution.

2018-07-31 20:23 UTC, artem-v commented on services-discovery/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
I talked to @aharonha about this indent issue in eclipse and looks like he found a solution.

2018-08-01 09:14 UTC, dmytro-lazebnyi submitted a review, later dismissed

2018-08-01 09:39 UTC, ronenhamias commented on services-api/pom.xml
>  <?xml version="1.0"?>
so we agreed on indent 2,2,2

2018-08-01 09:48 UTC, segabriel commented on services-api/src/main/java/io/scalecube/services/discovery/api/DiscoveryConfig.java
> +    private Map<String, String> tags = new HashMap<>();
maybe better use `Collections.emptyMap()` as a default value. 
And also in `DiscoveryConfig` c'tor `new HashMap(builder.tags)`

2018-08-01 10:37 UTC, artem-v approved these changes

2018-08-01 10:38 UTC, merged