Support tags
ronenhamias/scalecube-services pull request #36
Opened 2018-04-27 15:19 UTC by snripa

2018-04-27 16:03 UTC, artem-v reviewed
PR doesn work with latest `develop`

2018-04-27 16:26 UTC, ronenhamias commented on services/src/test/java/io/scalecube/services/RemoteServiceTest.java
> +        .withService(new GreetingServiceImplA()).withTag("Weight", "0.3").register()
i suggest the following api becouse now we register with tags but maybe we want to specify more things for service besides tags

so its like ServiceBuilder where service has tags
service......tag(....).register()  and we say register it.

```java

Microservices.builder()
    .service(new GreetingServiceImplA())
         .tag("Weight", "0.3")
         .tag("Version", "2.0")
         .register()
    .service(new GreetingServiceImplA()).tag("Weight", "0.3").register()
    .build()
```

lets say tommrow it will be:
```java
Microservices.builder()
    .service(new GreetingServiceImplA())
         .tag("Weight", "0.3")
         .auth(jwt) // or something else?
         .register()
    .service(new GreetingServiceImplA()).tag("Weight", "0.3").register()
    .build()
```

the prefix with is confusing as i would expect with to be a starting point like from()

else the meaning of with is actually set but becouse the object is immutable and its in the context of a builder there is no sense for with prefix its just redundent and make you wonder...
why the developer decided to put with here what it means ?.

2018-04-29 12:41 UTC, aharonha commented on services/src/main/java/io/scalecube/services/Microservices.java
> + *         Mono<String> asyncGreeting(String string);
What about backward compatibility?

2018-04-29 12:44 UTC, aharonha commented on services/src/main/java/io/scalecube/services/Microservices.java
> +    public Builder port(int port) {
change to servicePort?

2018-04-29 12:56 UTC, aharonha commented on services/src/main/java/io/scalecube/services/Reflect.java
> +    private void inject(Object[] services) {
use `iterable` rather then `Object[]`

2018-04-29 12:57 UTC, aharonha commented on services/src/main/java/io/scalecube/services/Reflect.java
> +      this.inject(this.microservices.services().toArray());
avoid `.toArray()`

2018-04-29 12:57 UTC, aharonha commented on services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java
> +  public static ServiceEndpoint scan(List<Microservices.ServiceInfo> serviceInstances, String host, int port,
add javadoc

2018-04-29 12:59 UTC, aharonha commented on services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java
> +        .filter(iAndTags -> iAndTags.serviceInterface.isAnnotationPresent(Service.class))
iAndTags?

2018-04-29 13:00 UTC, aharonha commented on services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java
> +          ContentType ctAnnotation = serviceInterface.getAnnotation(ContentType.class);
are we still using `ContentType` annotaion?

2018-04-29 13:01 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/Microservices.java
> + *         Mono<String> asyncGreeting(String string);
its not backward compatible hence v2.0

2018-04-29 13:02 UTC, aharonha commented on services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java
> +                String contentType = ContentType.DEFAULT;
are we still using `ContentType` annotaion?

2018-04-29 13:04 UTC, aharonha commented on services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java
> +  private static String merge(String lowPriority, String highPriority) {
Are we using this?

2018-04-29 13:08 UTC, aharonha commented on services/src/main/java/io/scalecube/services/transport/LocalServiceDispatchers.java
> +            default:
maybe add logging

2018-04-29 13:11 UTC, aharonha commented on services/src/test/java/io/scalecube/services/RemoteServiceTest.java
> +        if (success.getResult().contains("SERVICE_B_TALKING")) {
consider using some kind of reactive test assertion frameworks

2018-04-29 13:17 UTC, aharonha commented on services/src/test/java/io/scalecube/services/ServiceCallTest.java
> +    return Microservices.builder()
spaces?

2018-04-29 13:22 UTC, aharonha requested changes
see comments below

2018-04-29 13:25 UTC, aharonha approved these changes

2018-04-29 13:29 UTC, merged