Develop get rid of payload dep from service msg codec
ronenhamias/scalecube-services pull request #57
Opened 2018-04-30 17:11 UTC by artem-v

2018-04-30 18:53 UTC, ronenhamias commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/client/RSocketServiceClientAdapter.java
> +      ByteBuf[] bufs = codec.encodeMessage(request);
you always expects 2 buff?

2018-04-30 18:55 UTC, ronenhamias commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/client/RSocketServiceClientAdapter.java
> +      ByteBuf[] bufs = codec.encodeMessage(request);
maybe we should create 
ServicePayload
  ByteBuff header()
  ByteBuff data()

2018-04-30 19:25 UTC, ronenhamias commented on services-codec/src/main/java/io/scalecube/services/codec/ServiceMessageCodec.java
> +    return bufs;
return new MessageFrame(headerBuffer,dataBuffer);

2018-04-30 19:26 UTC, ronenhamias commented on services-codec/src/main/java/io/scalecube/services/codec/ServiceMessageCodec.java
> +  public ServiceMessage decodeMessage(ByteBuf dataBuffer, ByteBuf headersBuffer) {
decodeMessage(MessageFrame frame)

2018-04-30 19:27 UTC, ronenhamias commented
looks great to me +1
few suggestions to improvement if you would like to consider them

2018-05-02 07:22 UTC, snripa commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/client/RSocketServiceClientAdapter.java
> +      ByteBuf[] bufs = codec.encodeMessage(request);
it should be always 2 since we both encode and decode the payload, noone in the middle

2018-05-02 09:58 UTC, snripa requested changes

2018-05-02 09:58 UTC, snripa commented on rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/RSocketServiceTransport.java
> +    HeadersCodec headersCodec = HeadersCodec.getInstance(DEFAULT_HEADERS_FORMAT);
WDYT about having just one headers codec (lets say json) and not to let encode/decode HEADERS with another data format?

2018-05-02 09:58 UTC, snripa commented on services-codec/src/main/java/io/scalecube/services/codec/HeadersCodec.java
> +  void encode(OutputStream stream, Map<String, String> headers) throws IOException;
would u mind to change order of params?

2018-05-02 09:58 UTC, snripa commented on rsocket-transport/pom.xml
> +			<dependency>
stat's strange, dependencyManagement in child project...

2018-05-02 09:58 UTC, snripa commented on rsocket-transport/pom.xml
> +			<dependency>
stat's strange, dependencyManagement in child project...

2018-05-02 09:58 UTC, snripa commented on services-codec-jackson/pom.xml
> +      <version>${project.version}</version>
remove versions

2018-05-02 11:15 UTC, merged