Introduce services examples
ronenhamias/scalecube-services pull request #61
Opened 2018-05-03 15:13 UTC by ronenhamias

2018-06-19 10:39 UTC, artem-v requested changes

2018-06-19 10:39 UTC, artem-v commented on scalecube-services-examples/pom.xml
> +</project>
Plz add new line

2018-06-19 10:39 UTC, artem-v commented on scalecube-services-examples/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
Formatting is missing at this file. Indent is 4 but we have 2 in xmls.

2018-06-19 10:39 UTC, artem-v commented on scalecube-services-examples/src/main/java/io/scalecube/examples/helloworld/Example2.java
> +/**
New line is needed

2018-06-19 10:39 UTC, artem-v commented on scalecube-services-examples/src/main/java/io/scalecube/examples/orderbook/service/DefaultMarketDataService.java
> +
Why visibility qualifiers are missing

2018-06-19 10:39 UTC, artem-v commented on scalecube-services-examples/src/main/java/io/scalecube/examples/orderbook/service/OrderBookSnapshoot.java
> +
Visibility qualifiers are missing

2018-06-19 10:39 UTC, artem-v commented on scalecube-services-examples/src/main/java/io/scalecube/examples/orderbook/service/Order.java
> +
Here are private quaoifiers. Pls make sure u dont fotgot to put it everywhere.

2018-06-26 17:53 UTC, ronenhamias commented
closing this pull request and moving to:
https://github.com/scalecube/scalecube-services/pull/156

2018-06-26 17:53 UTC, closed without merging